'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import Icon from '@/components/ui/Icon';

export default function Integrations(){
 const [integration,setIntegration]=useState(null),[form,setForm]=useState({access_token:'',page_id:'',instagram_business_id:''}),[busy,setBusy]=useState(false),[msg,setMsg]=useState('');
 const load=()=>api.getMetaIntegration().then(d=>{setIntegration(d.integration);if(d.integration)setForm(f=>({...f,page_id:d.integration.page_id||'',instagram_business_id:d.integration.instagram_business_id||''}));}).catch(e=>setMsg(e.message)); useEffect(()=>{load();},[]);
 const connect=async e=>{e.preventDefault();setBusy(true);setMsg('');try{const d=await api.connectMeta(form);setIntegration(d.integration);setForm(f=>({...f,access_token:''}));setMsg(d.integration?.verified?'تم التحقق من الاتصال بنجاح.':`تم حفظ الإعدادات، لكن التحقق لم ينجح: ${d.integration?.verify_error||'راجع التوكن'}`);}catch(e){setMsg(e.message)}finally{setBusy(false)}};
 const disconnect=async()=>{setBusy(true);try{await api.disconnectMeta();setIntegration(null);setMsg('تم فصل حساب Meta.')}finally{setBusy(false)}};
 return <div className="dashboard-stack"><section className="page-intro"><div><span>META CONNECTION</span><h2>اربط النشر من داخل AdGenie.</h2><p>التوكن يتم حفظه مشفرًا في الـ Backend ولا يتم إرجاعه للمتصفح بعد الحفظ.</p></div></section>{msg&&<div className="notice">{msg}</div>}
 <section className="integration-grid"><article className="integration-card"><div className="integration-brand"><span className="meta-badge"><Icon name="facebook"/><Icon name="instagram"/></span><div><h3>Meta Platforms</h3><p>Facebook Page + Instagram Business</p></div></div><span className={`status ${integration?.verified?'success':'warning'}`}>{integration?.verified?'متصل ومتحقق':'غير متصل'}</span>{integration?.profile?.name&&<div className="connected-profile"><small>Connected as</small><b>{integration.profile.name}</b></div>}<form onSubmit={connect} className="integration-form"><label className="field"><span>Meta Access Token</span><input type="password" required={!integration} placeholder={integration?'محفوظ بالفعل — أدخل توكن جديد للتحديث':'Paste access token'} value={form.access_token} onChange={e=>setForm({...form,access_token:e.target.value})}/></label><label className="field"><span>Facebook Page ID</span><input value={form.page_id} onChange={e=>setForm({...form,page_id:e.target.value})}/></label><label className="field"><span>Instagram Business Account ID</span><input value={form.instagram_business_id} onChange={e=>setForm({...form,instagram_business_id:e.target.value})}/></label><div className="button-row"><button className="premium-button" disabled={busy}>{busy?'جارٍ التحقق...':integration?'تحديث الاتصال':'اتصال وفحص'}</button>{integration&&<button type="button" className="danger-button" onClick={disconnect}>فصل الحساب</button>}</div></form></article>
 <article className="panel meta-steps"><div className="panel-head"><div><small>SETUP GUIDE</small><h3>الخطوات داخل Meta</h3></div></div><ol><li><span>1</span><div><b>Meta for Developers</b><p>أنشئ App أو استخدم App موجود وأضف Facebook Login / Instagram Graph API حسب حالة الحساب.</p></div></li><li><span>2</span><div><b>الصلاحيات</b><p>للنشر تحتاج صلاحيات مناسبة للحساب والصفحة مثل pages_manage_posts و instagram_content_publish وفق مراجعة Meta.</p></div></li><li><span>3</span><div><b>IDs</b><p>أدخل Page ID وInstagram Business Account ID المرتبطين بالحساب المستخدم في التوكن.</p></div></li><li><span>4</span><div><b>Public Media URL</b><p>Meta يجب أن يقدر على الوصول لصورة الإعلان عبر رابط عام، لذلك اضبط MEDIA_PUBLIC_BASE_URL في الـ Backend عند النشر الإنتاجي.</p></div></li></ol></article></section></div>
}
