'use client';
import { useEffect, useState } from 'react';
import { api } from '@/lib/api';
import Icon from '@/components/ui/Icon';

export default function Ads(){
 const [campaigns,setCampaigns]=useState([]),[published,setPublished]=useState([]),[busy,setBusy]=useState(''),[msg,setMsg]=useState(''),[editing,setEditing]=useState(''),[copy,setCopy]=useState('');
 const load=()=>Promise.all([api.getCampaigns(),api.getPublishedAds()]).then(([c,p])=>{setCampaigns(c.campaigns||[]);setPublished(p.published_ads||[])}).catch(e=>setMsg(e.message));
 useEffect(()=>{load()},[]);
 const publish=async(c,platform)=>{setBusy(c.campaign_id+platform);setMsg('');try{await api.publishCampaign(c.campaign_id,platform);setMsg(`تم النشر على ${platform}.`);await load()}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const startEdit=(c)=>{setEditing(c.campaign_id);setCopy(c.selected_variation?.ad_copy||'')};
 const save=async(c)=>{setBusy(c.campaign_id+'save');setMsg('');try{await api.updateCampaignVariation(c.campaign_id,c.selected_variation_id,copy);setMsg('تم حفظ النص النهائي للإعلان.');setEditing('');await load()}catch(e){setMsg(e.message)}finally{setBusy('')}};
 const regen=async(c)=>{setBusy(c.campaign_id+'image');setMsg('جارٍ توليد صورة جديدة…');try{await api.regenerateCampaignImage(c.campaign_id,c.selected_variation_id);setMsg('تم توليد صورة جديدة وحفظها.');await load()}catch(e){setMsg(e.message)}finally{setBusy('')}};
 return <div className="dashboard-stack"><section className="page-intro"><div><span>AD LIBRARY</span><h2>الإعلانات المعتمدة والمنشورة.</h2><p>راجع النص والصورة، عدّل النسخة النهائية، ثم انشرها على القناة المناسبة.</p></div></section>{msg&&<div className="notice">{msg}</div>}<section className="ad-library">{campaigns.filter(c=>c.selected_variation).map(c=>{const v=c.selected_variation;const edit=editing===c.campaign_id;return <article className="ad-card" key={c.campaign_id}><div className="ad-image">{v.image_output?<img src={v.image_output} alt=""/>:<div className="image-failure"><b>لا توجد صورة مولدة</b><button onClick={()=>regen(c)} disabled={busy===c.campaign_id+'image'}>{busy===c.campaign_id+'image'?'جارٍ التوليد…':'توليد صورة الآن'}</button></div>}</div><div className="ad-body"><div className="ad-top"><span className="status neutral">{c.campaign_status||'selected'}</span><small>{c.brand_name}</small></div><h3>{v.marketing_angle||'Selected creative direction'}</h3>{edit?<div className="copy-editor"><textarea rows="12" value={copy} onChange={e=>setCopy(e.target.value)}/><div className="copy-editor-meta"><span>{copy.length} حرف</span><button onClick={()=>save(c)} disabled={busy===c.campaign_id+'save'}>{busy===c.campaign_id+'save'?'جارٍ الحفظ…':'حفظ النص'}</button></div></div>:<p>{v.ad_copy}</p>}<div className="ad-edit-row">{!edit&&<button onClick={()=>startEdit(c)}><Icon name="edit"/> تعديل النص</button>}<button onClick={()=>regen(c)} disabled={busy===c.campaign_id+'image'}><Icon name="sparkles"/> صورة جديدة</button></div><div className="ad-actions"><button onClick={()=>publish(c,'facebook')} disabled={busy}><Icon name="facebook"/> {busy===c.campaign_id+'facebook'?'جارٍ النشر...':'نشر Facebook'}</button><button onClick={()=>publish(c,'instagram')} disabled={busy}><Icon name="instagram"/> {busy===c.campaign_id+'instagram'?'جارٍ النشر...':'نشر Instagram'}</button></div></div></article>})}{!campaigns.some(c=>c.selected_variation)&&<div className="empty-state big"><Icon name="ads" size={34}/><b>لا يوجد إعلان معتمد بعد</b><p>أنشئ حملة، ثم اختر أحد الاتجاهات الثلاثة ليظهر هنا.</p></div>}</section><section className="panel"><div className="panel-head"><div><small>PUBLISH HISTORY</small><h3>سجل النشر</h3></div></div><div className="table-wrap"><table><thead><tr><th>المنصة</th><th>الحالة</th><th>Campaign ID</th><th>التاريخ</th><th>External ID</th></tr></thead><tbody>{published.map(a=><tr key={a.publish_id}><td>{a.platform}</td><td><span className={`status ${a.status==='published'?'success':'warning'}`}>{a.status}</span></td><td>{a.campaign_id?.slice(0,10)}…</td><td>{new Date(a.published_at).toLocaleString('ar-EG')}</td><td>{a.external_id||'—'}</td></tr>)}{!published.length&&<tr><td colSpan="5">لا يوجد سجل نشر حتى الآن.</td></tr>}</tbody></table></div></section></div>
}
