'use client';
import { useEffect, useMemo, useState } from 'react';
import { api } from '@/lib/api';
import Icon from '@/components/ui/Icon';

const emptyForm={brand_name:'',industry:'',description:'',website:'',brand_story:'',product_or_service:'',target_audience:'',audience_location:'',customer_pain_points:'',competitors:'',unique_selling_points:'',tone_of_voice:'',visual_style:'',brand_colors:'',default_cta:'',constraints:'',default_platforms:['facebook','instagram'],default_objective:'',default_offer:'',language:'ar',onboarding_step:4,onboarding_complete:true,logo_url:''};
const listToText=a=>Array.isArray(a)?a.join('\n'):''; const textToList=v=>(v||'').split('\n').map(x=>x.trim()).filter(Boolean);

export default function Projects(){
 const [brands,setBrands]=useState([]),[limit,setLimit]=useState(1),[form,setForm]=useState(emptyForm),[editing,setEditing]=useState(null),[busy,setBusy]=useState(false),[message,setMessage]=useState('');
 const load=()=>api.getBrands().then(d=>{setBrands(d.brands||[]);setLimit(d.limit||1);}).catch(e=>setMessage(e.message));
 useEffect(()=>{load();},[]);
 const canAdd=brands.length<limit;
 const openNew=()=>{setEditing('new');setForm(emptyForm);setMessage('');};
 const openEdit=b=>{setEditing(b.brand_id);setForm({...emptyForm,...b,customer_pain_points:listToText(b.customer_pain_points),competitors:listToText(b.competitors),unique_selling_points:listToText(b.unique_selling_points),brand_colors:listToText(b.brand_colors)});setMessage('');};
 const payload=()=>({...form,customer_pain_points:textToList(form.customer_pain_points),competitors:textToList(form.competitors),unique_selling_points:textToList(form.unique_selling_points),brand_colors:textToList(form.brand_colors),onboarding_step:4,onboarding_complete:true});
 const save=async(e)=>{e.preventDefault();setBusy(true);setMessage('');try{const res=editing==='new'?await api.createBrand(payload()):await api.updateBrand(editing,payload()); const brand=res.brand; const file=e.currentTarget.logo?.files?.[0]; if(file) await api.uploadBrandLogo(brand.brand_id,file); setEditing(null);await load();setMessage('تم حفظ المشروع بنجاح.');}catch(err){setMessage(err.message);}finally{setBusy(false);}};
 return <div className="dashboard-stack">
  <section className="page-intro"><div><span>BRAND INTELLIGENCE</span><h2>عرّف AdGenie على كل مشروع قبل أي حملة.</h2><p>كل معلومة هنا تدخل في سياق التوليد لتقليل الهلوسة والحفاظ على أسلوب البراند.</p></div><button className="premium-button" disabled={!canAdd} onClick={openNew}><Icon name="plus"/> مشروع جديد</button></section>
  <div className="quota-strip"><div><span>المشاريع المستخدمة</span><b>{brands.length} / {limit}</b></div><div className="quota-bar"><i style={{width:`${Math.min(100,(brands.length/Math.max(limit,1))*100)}%`}}/></div></div>
  {message&&<div className="notice">{message}</div>}
  <section className="project-cards">{brands.map(b=><article className="project-card" key={b.brand_id}><div className="project-card-top"><div className="project-logo">{b.logo_url?<img src={b.logo_url} alt=""/>:<span>{(b.brand_name||'P')[0]}</span>}</div><span className="status success">Brand Brain ready</span></div><h3>{b.brand_name}</h3><p>{b.description||'لا يوجد وصف بعد.'}</p><div className="project-meta"><span>{b.industry||'General'}</span><span>{b.audience_location||'Audience not set'}</span></div><button className="secondary-button" onClick={()=>openEdit(b)}>تعديل بيانات المشروع</button></article>)}</section>
  {editing&&<div className="modal-shell"><button className="modal-backdrop" onClick={()=>setEditing(null)}/><div className="project-modal"><div className="modal-head"><div><small>PROJECT ONBOARDING</small><h3>{editing==='new'?'إنشاء مشروع جديد':'تعديل المشروع'}</h3></div><button className="icon-button" onClick={()=>setEditing(null)}><Icon name="x"/></button></div><form onSubmit={save} className="project-form">
    <div className="form-section"><h4>الهوية الأساسية</h4><div className="field-grid"><Field label="اسم البراند" name="brand_name" value={form.brand_name} set={setForm} required/><Field label="المجال" name="industry" value={form.industry} set={setForm}/><Field label="الموقع" name="website" value={form.website} set={setForm}/><label className="file-field"><span>Logo PNG / JPG / WebP</span><input name="logo" type="file" accept="image/png,image/jpeg,image/webp"/><div><Icon name="upload"/> اختر اللوجو</div></label></div><Area label="وصف المشروع" name="description" value={form.description} set={setForm}/><Area label="قصة البراند والخلفية" name="brand_story" value={form.brand_story} set={setForm}/></div>
    <div className="form-section"><h4>المنتج والجمهور</h4><Area label="المنتج أو الخدمة" name="product_or_service" value={form.product_or_service} set={setForm}/><div className="field-grid"><Field label="الجمهور المستهدف" name="target_audience" value={form.target_audience} set={setForm}/><Field label="الموقع الجغرافي" name="audience_location" value={form.audience_location} set={setForm}/></div><Area label="أهم نقاط الألم — كل نقطة في سطر" name="customer_pain_points" value={form.customer_pain_points} set={setForm}/><Area label="نقاط التميز — كل نقطة في سطر" name="unique_selling_points" value={form.unique_selling_points} set={setForm}/><Area label="المنافسون — كل اسم في سطر" name="competitors" value={form.competitors} set={setForm}/></div>
    <div className="form-section"><h4>الصوت والهوية البصرية</h4><div className="field-grid"><Field label="Tone of voice" name="tone_of_voice" value={form.tone_of_voice} set={setForm}/><Field label="CTA افتراضي" name="default_cta" value={form.default_cta} set={setForm}/></div><Area label="الستايل البصري المطلوب" name="visual_style" value={form.visual_style} set={setForm}/><Area label="ألوان البراند HEX — كل لون في سطر" name="brand_colors" value={form.brand_colors} set={setForm}/><Area label="قيود مهمة لا يجب تجاوزها" name="constraints" value={form.constraints} set={setForm}/></div>
    <div className="modal-actions"><button type="button" className="glass-button" onClick={()=>setEditing(null)}>إلغاء</button><button className="premium-button" disabled={busy}>{busy?'جارٍ الحفظ...':'حفظ Brand Brain'}</button></div>
  </form></div></div>}
 </div>;
}
function Field({label,name,value,set,required}){return <label className="field"><span>{label}</span><input required={required} value={value||''} onChange={e=>set(f=>({...f,[name]:e.target.value}))}/></label>}
function Area({label,name,value,set}){return <label className="field full"><span>{label}</span><textarea rows="4" value={value||''} onChange={e=>set(f=>({...f,[name]:e.target.value}))}/></label>}
